import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import { Providers } from "./providers";
import Navbar from "@/Components/Navbar";
import FooterBro from "@/Components/Footer";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Rent Drone | Ardiminda Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      {/* <Providers> */}
        <Navbar/>
        {children}
      {/* </Providers> */}

      <FooterBro/>
      </body>
    </html>
  );
}
